### ISSUE TITLE
How to get &ft from lua

### ISSUE THREAD

**Issue by sandangel** [nanotee/nvim-lua-guide#105]
Hi, I checked the doc but it seems like there is no option to get specific vim variable from lua. Is it possible?

**Comment by marcusatiliusregulus** [comment]
yes see `:h lua-vim-variables`. however for the value of an option use for example `:lua print(vim.o.filetype)`

**Comment by sandangel** [comment]
hi, I checked that doc already, that only mentioned `g:`, `b:` ... vars, but doesn't mention something like `&ft` or `&buftype`. So you mean for those vars we need to check the `vim.o` instead? Do you think this worth mention in the README as well? Thanks for pointing that out for me.

**Comment by nanotee** [comment]
As marcusatiliusregulus notes, `vim.o` is the closest equivalent for options. Hopefully  [this commit](https://github.com/nanotee/nvim-lua-guide/commit/be74c1a1aac748396e16628ebbc2a79f76eece67) makes things a little clearer

**Comment by sandangel** [comment]
yeah, that would be perfect. thank you. 😊
