### ISSUE TITLE
Discussion of lua plugins and packages

### ISSUE THREAD

**Issue by clason** [nanotee/nvim-lua-guide#11]
With `packer.nvim`, many people might be tempted to switch from `vim-plug` to the native package system. There are some gotchas with that, since packages are not available during the time `init.vim` is read.

Things to mention, maybe (I'm sure there are others):
* a link to a good description (does anyone know of any) of the way native packages work
* using `vim.cmd [[packadd! plugin]]` in the lua code
* adding a vimscript shim to `.nvim/config/plugin` that `packadd`s and `require`s the lua code from `.nvim/config/lua` using the plugin
* ...

**Comment by nanotee** [comment]
Having used native packages for some time now I'm well aware of some of their idiosyncrasies. To be honest I still haven't completely wrapped my head around how they work, despite having read the documentation several times. My current understanding is thus:

- `start` packages are loaded automatically after processing `init.vim`
- Both `opt` and `start` packages can be loaded manually with `:packadd`
- `:packadd!` will only add a package to the `runtimepath` without sourcing any of its scripts (useful for `require`ing Lua modules or calling autoload functions from one's `init.vim`)
- `start` packages can be loaded earlier with `:packloadall`
- One might expect `:packloadall!` to add all `start` packages to the `runtimepath` without sourcing their scripts, which would be *very* useful for the problem at hand, but instead it... reloads all `start` packages?????
- If you want to `require` a Lua module or call an autoload function from `init.vim`, you first have to `:packadd!` the package, even if it's in `start`
- But if you do the same from `plugin/foo.vim`, it works without `:packadd!`??? So packages are loaded *after* `init.vim` but *before* `plugin/foo.vim`?

The `+packages` feature was inherited from Vim if I'm not mistaken, so it probably wasn't designed with Neovim users `require`ing Lua modules left and right in mind. Still, I feel like expecting users to know all the nuances of native packages is going to lead to *some* amount of frustration...

The growing popularity of Lua plugins is going to expose users of native packages to these gotchas, so the guide should definitely mention them.

**Comment by clason** [comment]
I think you summarize the situation (and the idiosyncrasies) quite well, at least as far as my limited understanding goes. The bullet list would be a good start for a corresponding section, too. 

Yes, packages are a vim feature, and definitely not built with lua packages in mind. (@norcalli had some ideas on building a new system for them from the ground up, which would have advantages and disadvantages -- certainly, lua-only plugins would be a reasonable watershed for such a move.)
