### ISSUE TITLE
Can we use this guide in Neovim?

### ISSUE THREAD

**Issue by dundargoc** [nanotee/nvim-lua-guide#120]
Hey. This guide is awesome. Can we use it (with some modifications) in neovim?

The PR if you're interested: https://github.com/neovim/neovim/pull/21137

**Comment by nanotee** [comment]
I'd actually be relieved if the Neovim project itself took ownership of the guide. I haven't had the time/energy to work on it in a while and the idea of there being another source of truth besides the official documentation doesn't sit right with me.

**Comment by dundargoc** [comment]
OK, awesome. Thanks!

**Comment by clason** [comment]
Thank you! Your guide was invaluable in getting the Lua ecosystem up and running! We really appreciate your work that went into this guide, especially during the early days where everything was a moving target. There's a reason that the matrix bot has a dedicated `!guide` command ;)
