### ISSUE TITLE
Lua Functions

### ISSUE THREAD

**Issue by tjdevries** [nanotee/nvim-lua-guide#2]
This is just a drive by comment since we were chatting in gitter.

You can do something like this (which you can't do with `v:lua`)

```vim
lua X = function(k, v) return string.format("%s:%s", k, v) end
echo map([1, 2, 3], luaeval("X"))
```

Do with this information as you wish ;)

**Comment by nanotee** [comment]
Thank you for the example! I'll think I'll add it to the section about `luaeval()`

**Comment by tjdevries** [comment]
Cool :+1: Great guide. Really appreciate it!
