### ISSUE TITLE
Add example config for sumneko for Lua

### ISSUE THREAD

**Issue by clason** [nanotee/nvim-lua-guide#21]
This is a very frequently asked question on Gitter, especially "how can I get lsp to recognize vim global"?

Until https://github.com/tjdevries/nlua.nvim is ready, it might be good to have an example config here to link to. Mine is the following (which is not uncontroversial, especially the `disable` on the diagnostics):

```lua
require'lspconfig'.sumneko_lua.setup{
  settings = {
    Lua = {
      runtime = {
        version = "LuaJIT",
        path = vim.split(package.path, ';'),
      },
      workspace = {
        library = {
          [vim.fn.expand("$VIMRUNTIME/lua")] = true,
          [vim.fn.expand("$VIMRUNTIME/lua/vim/lsp")] = true,
        },
      },
      diagnostics = {
        globals = {"vim"},
        disable = {"lowercase-global", "unused-function"},
      },
      completion = {
        keywordSnippet = "Disable",
      },
    },
  },
}
```

**Comment by nanotee** [comment]
Ah yeah, I think it'd be a good idea to put this in so newcomers can have a better experience writing Lua.

I haven't used sumneko in a while (I ran into issues regarding memory consumption). I'm using [Alloyed/lua-lsp](https://github.com/Alloyed/lua-lsp/), so I'd like to provide snippets for both language servers

Just so I understand correctly: we want to answer "how to stop the linter from screaming at the vim global" and "how do I get autocomplete for the nvim stdlib"?
