### ISSUE TITLE
Show how to call :echom / do print debugging

### ISSUE THREAD

**Issue by Julian** [nanotee/nvim-lua-guide#24]
As someone trying to write my absolute first line of nvim Lua, I scanned the README hoping it'd tell me what to put in my `init.lua` to just make something show up in `:messages` and prove things were running.

(I assume the right way to do so is to perhaps execute `echom` on `vim` but yeah may be nice to explicitly call out.)

Perhaps related to #5

**Comment by nanotee** [comment]
Looking at `:help lua-commands`, the built-in `print()` function is wired to the message area instead of standard output:

```
The Lua print() function redirects its output to the Nvim message area, with
arguments separated by " " (space) instead of "\t" (tab).
```

This isn't immediately obvious from reading the guide though, and people might want to test that everything is working correctly. I'll add a short paragraph about this, thank you for the suggestion!

**Comment by Julian** [comment]
Interesting -- `print` was the first thing I tried and *didn't* see the output in `:messages`, but that likely instead means the thing I tried was indeed not running :D

And yeah thanks for writing this!

**Comment by clason** [comment]
One small gotcha people might not expect is that a `silent!` in a command also prevents Lua `print` output. So
```vim
nnoremap silent! <leader>l :lua print('foo')<cr>
```
in fact prints nothing when entering `<leader>l`.

**Comment by nanotee** [comment]
@clason Did you mean `nnoremap <silent>`? I did a few tests and both of these mappings seem to be equivalent:

```vim
nnoremap <silent> <leader>l :echomsg 'foo'<CR> " prints 'foo'
nnoremap <silent> <leader>l :lua print('foo')<CR> " prints 'foo'
```

**Comment by clason** [comment]
No, I meant what I wrote (`:h silent`). It may in fact not be _very_ surprising, although I have repeatedly added debug `print` statements to Lua functions I call via `silent!` and then wondering why I didn't see that output (because I didn't connect the vimscript command with the Lua function)...
