### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MurdeRMelodY** [nanotee/nvim-lua-guide#35]
How to disable word/tag/buffer based completions?

**Comment by nanotee** [comment]
Hello!

I'm not sure what you're asking about exactly, does your question have to do with Lua or is this more of a general question about setting up Neovim? If you're having trouble setting up Neovim, the [Gitter channel](https://gitter.im/neovim/neovim) or the [discussions page](https://github.com/neovim/neovim/discussions/) are probably a better fit as you're more likely to get an answer

**Comment by MurdeRMelodY** [comment]
My bad, I think it might be a completion-nvim issue. I'm getting words in buffers in the autocomplete menu.
