### ISSUE TITLE
Could you unlink [Using LibUV in Neovim]?

### ISSUE THREAD

**Issue by kevinhwang91** [nanotee/nvim-lua-guide#36]
![image](https://user-images.githubusercontent.com/17562139/105639564-0d962500-5eb4-11eb-9ace-15a58133b93e.png)

`stdio = {stdout,stderr}` is wrong, it should be `stdio = {nil, stdout,stderr}`.

This tutorial about libuv wastes my time when I develop a plugin that needs libuv.

Hope another gets rid of this wrong tutorial.

**Comment by nanotee** [comment]
That's odd, on my end the order doesn't seem to matter. The code works even if the table only contains `stdout`. I'll have to investigate this a bit more, the LibUV documentation can be a bit sparse sometimes...

**Comment by kevinhwang91** [comment]
Great! If the issue is gone, free feel to delete this issue or rename its title. :)

**Comment by nanotee** [comment]
This has been fixed upstream, closing!
