### ISSUE TITLE
Mention abbrev

### ISSUE THREAD

**Issue by Th3Whit3Wolf** [nanotee/nvim-lua-guide#37]
I couldn't find any information on neovim lua abbrev or noreabbrev in your guide.

**Comment by nanotee** [comment]
I'm not aware of any Lua-specific mechanism related to abbreviations, did you have something in mind besides `vim.cmd 'abbrev foo bar'`?

**Comment by Th3Whit3Wolf** [comment]
I was hoping you would know something actually. I think that would work. Are you aware of any plans to implement a lua api for it?

**Comment by nanotee** [comment]
The core devs are probably more qualified to answer this than I am, but a brief look at the issue tracker tells me nothing has been planned so far (though you could always create an issue yourself if you'd like to suggest adding such an API).

There's a pretty nice wrapper for ex commands in [norcalli/nvim.lua](https://github.com/norcalli/nvim.lua/):

```lua
local api = vim.api

local ex = setmetatable({}, {
    __index = function(t, k)
      local command = k:gsub("_$", "!")
      local f = function(...)
        return api.nvim_command(table.concat(vim.tbl_flatten {command, ...}, " "))
      end
      rawset(t, k, f)
      return f
    end
  });

ex.abbrev('foo', 'bar')
```

It's still using `nvim_command` under the hood, but it definitely feels more "lua-ish"

**Comment by Th3Whit3Wolf** [comment]
I like it

**Comment by matu3ba** [comment]
belongs to advanced setup or guide after #40 ist finished.

**Comment by nanotee** [comment]
Closing this as there's currently no way to create abbreviations in Lua aside from `vim.cmd`

**Comment by n8henrie** [comment]
I check back every few months to see if there is a better solution for this.

Looks like one can now (0.8) do: 

```
vim.api.nvim_cmd({
  cmd = "inoreabbrev",
  args = {
    "ddebug",
    [[fmt.Printf("%#v\n",)<LEFT>]],
  },
}, {})
```

However I haven't figured out a way to specify an equivalent for e.g. `inoabbrev`
