### ISSUE TITLE
Lua 'require' loading modules

### ISSUE THREAD

**Issue by BigfootN** [nanotee/nvim-lua-guide#38]
Hello,

I am having troubles loading modules from `init.lua`.

For all my plugins I use `vim-plug`. I recently decided to use `completion-nvim`. Unfortunately, when loading the module:

```lua
local completion = require'completion'
```

I get:

```
E5113: Error while calling lua chunk: ~/.config/nvim/init.lua:6: module 'completion' not found:
        no field package.preload['completion']
        no file './completion.lua'
        no file '/usr/share/luajit-2.0.5/completion.lua'
        no file '/usr/local/share/lua/5.1/completion.lua'
        no file '/usr/local/share/lua/5.1/completion/init.lua'
        no file '/usr/share/lua/5.1/completion.lua'
        no file '/usr/share/lua/5.1/completion/init.lua'
        no file './completion.so'
        no file '/usr/local/lib/lua/5.1/completion.so'
        no file '/usr/lib/lua/5.1/completion.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

I know the files modules are loaded via the paths contained in `package.path` but since it is impossible (if I'm not mistaken) to have recursive patterns in lua, I don't wish to add every package/neovim extensions paths in `package.path`.

Is there a more simple way ?

Thank you very much in advance for any help.

**Comment by nanotee** [comment]
Hello!

I'm not sure what the issue is here, I can't reproduce on my end. Are you calling `require'completion'` before `call plug#end()`?

**Comment by BigfootN** [comment]
Thank you for your quick response.

In fact I have call `vim-plug` from `init.vim` and load/require from `init.lua`.

Thank you for your help.

**Comment by nanotee** [comment]
Mhh, it's kind of hard to debug without knowing what your config looks like

> In fact I call `vim-plug` from `init.vim` and load/require from `init.lua`.

Do you mean you have both a `~/.config/nvim/init.vim` file and a `~/.config/nvim/init.lua` file?
`:help config` says it's an error to use both at the same time

If that's not the case, make sure the call to `require'completion'` happens _after_ `call plug#end()` in your `init.vim`

(The [Neovim Gitter channel](https://gitter.im/neovim/neovim) and the [Neovim discussions page](https://github.com/neovim/neovim/discussions/) are probably more appropriate for these kinds of support questions, it's likely you'll get more eyeballs on your problem :slightly_smiling_face:)

**Comment by BigfootN** [comment]
Thank you very much for your precious help.

> Do you mean you have both a ~/.config/nvim/init.vim file and a ~/.config/nvim/init.lua file?
:help config says it's an error to use both at the same time

Indeed, I think that's the problem. Thank you for your time :slightly_smiling_face:
