### ISSUE TITLE
Mention setting environment variables

### ISSUE THREAD

**Issue by alexaandru** [nanotee/nvim-lua-guide#50]
Hello,

First of all, thank you for this amazing guide!!! I am finally VimL free :-) and much of it is thanks to this guide :-)

One of the last issues I tackled was setting environment variables in `init.lua`. It would be nice if the guide would mention that as well: in `init.vim` it was as easy as (for example) `let $GOFLAGS='-tags=development'` however I could not find any immediate/obvious way to achieve that in `init.lua` short of using `vim.cmd(...)`.

After some more digging, I finally found `setenv()` so settled for `vim.fn.setenv("GOFLAGS", "-tags=development")` which seems somewhat nicer.

Cheers!

**Comment by nanotee** [comment]
Thank you very much! Happy to hear this was useful :)

Another way to get/set environment variables is `:help vim.env`. It's a nicer wrapper around `setenv()` and `getenv()` that looks pretty similar to its Vimscript counterpart

**Comment by alexaandru** [comment]
Completely missed that, and it was right there with `vim.g` & friends :) Thank you once again, this is much nicer indeed :)
