### ISSUE TITLE
Update for breaking `vim.fn` change 

### ISSUE THREAD

**Issue by clason** [nanotee/nvim-lua-guide#52]
Neovim just merged https://github.com/neovim/neovim/pull/13875, which makes calling `vim.fn.foo` an error if `vim.api.foo` exists. This makes for an easier recommendation in the corresponding section :)

**Comment by matu3ba** [comment]
@clason You could also file a PR ;-)

**Comment by nanotee** [comment]
Thanks for the reminder!
