### ISSUE TITLE
Check if feature exists

### ISSUE THREAD

**Issue by ibraheemdev** [nanotee/nvim-lua-guide#54]
Is there a way to check if a vim feature exists? In vimscript, I can use:
```vim
if exists('+termguicolors')
  set termguicolors
end
```
Is there an equivalent in lua?

**Comment by nanotee** [comment]
`exists()` is a Vimscript function, so you can call it like this in Lua: `vim.fn.exists()`

**Comment by ibraheemdev** [comment]
@nanotee Ah, perfect. Thanks!
