### ISSUE TITLE
More explicit warning about boolean conversion

### ISSUE THREAD

**Issue by clason** [nanotee/nvim-lua-guide#58]
Converting your `init.vim` to `init.lua` is the new sport, it seems. One thing that I've seen people being bitten by repeatedly is converting something like 
```vim
let g:foo = 1
```
to 
```lua
vim.g.foo = true
```
which of course won't work since Lua `true` gets converted to `v:true`, which is not the same as `1`. (Same for `false` and `v:false` vs. `0`.)

I think it would be good to add a big, fat, caveat somewhere -- but where? The conversion itself is mentioned under "Accessing Lua from Vimscript", but it should probably be repeated on the converse side as well.

**Comment by nanotee** [comment]
I've added some notes about this in #59, thanks for notifying me

**Comment by clason** [comment]
Maybe add a sentence for safety like "This means that `let g:foo = 1` must be written as `vim.g.foo = 1`, since `1 != v:true` in VimL`?  (Basically adding that vim does _not_ have Boolean type conversion, so doing this will be an error?)

It's implicit in what you wrote, but maybe a bit _too_ implicit ;)
