### ISSUE TITLE
Update discussion of vim.cmd

### ISSUE THREAD

**Issue by clason** [nanotee/nvim-lua-guide#61]
Since https://github.com/neovim/neovim/commit/8402865cbad2e905bd841c3d9054f1027898e750, `vim.cmd` is now an alias to `vim.api.nvim_exec()` instead of `vim.api.nvim_command()`. (This should allow `vim.cmd` to work correctly with multi-line vimscript, too.)

**Comment by nanotee** [comment]
I saw that PR but forgot to update this section, thanks for the reminder!
