### ISSUE TITLE
Update section on vimscript options for vim.opt 

### ISSUE THREAD

**Issue by clason** [nanotee/nvim-lua-guide#63]
https://github.com/neovim/neovim/pull/13479 just got merged :tada: with the following changes:

* `vim.o` (set global option) was renamed to `vim.go`
* a _new_ `vim.o` was added that behaves (essentially) like `set` (is expected to -- meaning there may be weird corner cases)
* `vim.opt` was added to allow a more "luanatic" way of setting and getting (in particular, appending) options.

The docs are quite good and explicit, so maybe it's not necessary to repeat much (or just copy the examples from the docs), but the change in `vim.o` meaning should be reflected.

**Comment by nanotee** [comment]
Thank you (once again!) for the reminder. Hopefully what I've added in 40d7b05 and #64 is sufficient. Very exciting feature!

**Comment by clason** [comment]
No worries! Sorry for just dropping these reminders on you rather than actually helping out with a PR...

And thanks (again!) for this excellent guide, it's really helpful!
