### ISSUE TITLE
Neovim now sources Lua files from config directories

### ISSUE THREAD

**Issue by clason** [nanotee/nvim-lua-guide#67]
Now that https://github.com/neovim/neovim/pull/14686 is merged, neovim sources Lua files from the usual config directories directly during startup (after all vim files are sourced in the corresponding directory).

Also `:source foo.lua` is now a valid alternative to `:luafile foo.lua`.

As a bonus, `:<range>source` works on Lua code.

**Comment by nanotee** [comment]
Already done! https://github.com/nanotee/nvim-lua-guide/commit/e549b0d10f59c9678bb52dac7684f2076a403232 Really exciting news.

(I'll keep this open because I still need to talk about the `:source`/`:runtime` stuff, thanks for opening this issue)

**Comment by clason** [comment]
Yep, works quite well. Even colorschemes work (like `colorscheme moonberg` if `moonberg.lua` is in `colors`) -- not that this will buy you anything since it'll basically have to be a lot of `vim.cmd[[hi foo ...]]`, but when has that ever stopped anyone ;)

**Comment by clason** [comment]
Maybe mention the order of execution (all vim files, then all lua files, by directory)? That's in the docs, but may be good to know in that context?

**Comment by clason** [comment]
A few advantages I noticed which may or may not be worth mentioning:
1. putting things in `plugin/foo.lua` is slightly faster than using `require'foo'` with `lua/foo.lua` (due to the overhead `require` has); the difference is not great but measurable;
2. `plugin/foo.lua` does _not_ shadow a Lua module of the same name in `lua` (again, because no `require` is involved), which means that you can put, e.g., your `packer` config into `packer.lua` and not get weird errors;
3. after https://github.com/neovim/neovim/pull/14788 is merged, these will show up in the `--startuptime` profile

**Comment by nanotee** [comment]
#68 should cover everything. Thanks for your valuable suggestions, I find them very helpful!
