### ISSUE TITLE
[Request] Do a PR to merge into neovim's help

### ISSUE THREAD

**Issue by tricktux** [nanotee/nvim-lua-guide#7]
I find myself constantly referencing this guide. Thanks a lot it's super awesome. It would be amazing if it was merged into master.

Thanks! ❤️

**Comment by nanotee** [comment]
Thank you for the kind words! I'm glad this guide is useful to you :)

In its current state, I don't think it could be merged as-is: some sections need to be polished/finished and there's a lot of overlap with the existing documentation. I'd be happy to contribute parts of it, though!

In the meantime, I could try and convert it to a vim help file so people could install it as a plugin. You could then generate tags for it and you'd be able to use it as a quick reference. Is this something you would find useful?

**Comment by tricktux** [comment]
>Is this something you would find useful?

I would love that! I think turning the page into a help page is an excellent idea

I agree there's some repeated info. But the examples are pretty awesome. I would like to use this issue to suggest chunks, that I think neovim help could benefit from. It's that's okay?

Thanks!

**Comment by nanotee** [comment]
Sure! Knowing what people find useful can help improve the guide, too

**Comment by svermeulen** [comment]
Yeah this guide is awesome.  Thanks for this

**Comment by clason** [comment]
> In the meantime, I could try and convert it to a vim help file so people could install it as a plugin. You could then generate tags for it and you'd be able to use it as a quick reference. Is this something you would find useful?

To be honest, I think it's more accessible and findable as markdown/html -- in fact, I'd rather have *nvim* help as a proper HTML documentation, with a table of contents sidebar and a search field (like readthedocs.org, for example)...

**Comment by nanotee** [comment]
> (Which is of course not an argument against providing this guide _also_ as a vimdoc plugin!)

That's the plan! The guide now has a [vimdoc version](https://github.com/nanotee/nvim-lua-guide/blob/master/doc/nvim-lua-guide.txt) in addition to the markdown file.

I do wish the format was a little nicer to work with, especially regarding conversion. This would make it much easier to output HTML or Markdown

**Comment by matu3ba** [comment]
related: create and link a cheat sheet like [this](https://devhints.io/vimscript) for newcomers.

**Comment by tricktux** [comment]
Thanks again for all there great references posted here! I think this issue can be closed. Is up to you @nanotee ....
