### ISSUE TITLE
Reference doc for the global vim object

### ISSUE THREAD

**Issue by dwoznicki** [nanotee/nvim-lua-guide#76]
Is there a document for the "standard library" exposed via the global `vim` object? I see some functions documented when I run `:h lua-vim`, but quite a few of them are not. I'm trying to figure out what some functions (e.g. `vim.api.nvim_list_wins`) do and what their call signatures are.

If it helps, I'm on version `NVIM v0.6.0-dev+106-g545e05d2f`.

**Comment by alexaandru** [comment]
The one you discovered already, [:h lua](https://neovim.io/doc/user/lua.html) is the Lua "editor stdlib", these are Lua additions that complement the nvim API. And of course, you have documentation for the latter as well, via [:h api](https://neovim.io/doc/user/api.html).

Cheers!

**Comment by nanotee** [comment]
As @alexaandru notes, `api` functions are their own thing. They're exposed to Vimscript and remote plugins and are thus not Lua-specific, which is why they're not documented under `:h lua-vim`

**Comment by dwoznicki** [comment]
Thanks for the help. That all makes sense. Do you think it's worth making a quick note in the #the-vim-namespace section, or is that out of scope for this repo?

**Comment by nanotee** [comment]
Done! Seems like people find the distinction confusing so thanks for the suggestion!
