### ISSUE TITLE
how to read the command arguments `:command arg1 arg2` with lua

### ISSUE THREAD

**Issue by matu3ba** [nanotee/nvim-lua-guide#84]
[related question](https://github.com/nvim-telescope/telescope-project.nvim/issues/66#issuecomment-950230200).

Shells provide aliases to abbreviate typing for functionality. For this access to the command arguments (not the one neovim was started with) from lua would be necessary.

An alternative would be linking or providing a description 1. how to pipe shell output to telescope/another lua program and 2. how to sync `pwd` of the shell and `lwd` or `gwd` (:lcd and :cd folder) of neovim.

Does this description make sense to you?

**Comment by nanotee** [comment]
Sorry, I'm having trouble understanding the issue, is this about creating user-defined commands? I'm not sure I understand how it relates to Lua

**Comment by matu3ba** [comment]
I think I messed up. If the command is defined in vimscript, on should trivially use vimscript to handle the passed arguments.
