### ISSUE TITLE
Improper handling of relative paths with spaces

### ISSUE THREAD

**Issue by SimonMandlik** [nanotee/nvim-lua-guide#89]
I'm using a `'filename', path=1, symbols = { unnamed = '' }` section in the following scenario

```
❯ tree ~/With\ Space/
/Users/simon.mandlik/With\ Space/
└── test.txt

0 directories, 1 file
```

If I `cd` into the `"With Space"` dir and open `test.txt`, the following is shown in lualine:

![image](https://user-images.githubusercontent.com/16707112/148188303-ce066325-fa5c-4f74-b3f5-168b2e07e5c5.png)

`:pwd` in neovim returns `/Users/simon.mandlik/With Space`

**Comment by nanotee** [comment]
Sorry, I'm not sure I understand, was this issue meant for the lualine repository?

**Comment by SimonMandlik** [comment]
Yes it was, apologies..
