### ISSUE TITLE
How to let `vim.cmd` accept the range from visual selection

### ISSUE THREAD

**Issue by nyngwang** [nanotee/nvim-lua-guide#90]
Here is an example:
```
:'<,'>Commentary
```
The command I tried is:
```
vim.cmd("'<,'>Commentary")
```
but it doesn't work.

**Comment by nanotee** [comment]
Hello,

For Neovim-related questions, I recommend either the official [Discourse forum](https://neovim.discourse.group) or the [Matrix room](https://app.element.io/#/room/#neovim:matrix.org). You're more likely to get an answer on dedicated support channels (few people look at this issue tracker)
