### ISSUE TITLE
Create keymap to open new file adjacent to current file

### ISSUE THREAD

**Issue by justb3a** [nanotee/nvim-lua-guide#92]
Hi,

I'm struggeling a while now with this and tried serveral solutions. My goal is to use the edit command with the path of the currently edited file filled in:

```vim
nnoremap <leader>e :e <C-R>=expand("%:p:h") . "/" <CR>
```

```lua
vim.api.nvim_set_keymap('n', '<leader>e', '<cmd>e ???<cr>', {silent = true, noremap = true})
```
Using it directly just works as expected.

I tried to wrap `<C-R>` in the `termcodes` function and several other ways, but none of them worked. Maybe there is even a better way to solve this with lua. Any help is appreciated 🙏🏻

**Comment by nanotee** [comment]
Hi,

Try replacing `<Cmd>` with a `:`. `<Cmd>` executes the command directly without changing modes which is why `<C-R>` doesn't work.

(As a sidenote, questions like these are more likely to get an answer on dedicated support forums like the [Neovim Discourse](https://neovim.discourse.group/))

**Comment by justb3a** [comment]
Tried this as well, didn't work at first glance. Now I tried it again, I was waiting for the path being shown so that I could extend it. Now I discovered that only if you type something, the path will appear and then it works. Thanks.

(Thanks for the sidenote link ;) )

**Comment by gegoune** [comment]
You shouldn't have to type anything apart of the keymap itself. I suspect you have another keymap for `<leader>e<something>` and nvim waits for more input. Try: `:nmap <leader>e` to see what mappings you have set up.

**Comment by nanotee** [comment]
> Now I discovered that only if you type something, the path will appear and then it works.

Does removing `silent = true` fix it?

**Comment by clason** [comment]
PSA: There's a full Lua API now (`vim.keymap.*`), so I'd probably focus on just that now.

**Comment by justb3a** [comment]
I use a custom keymap function, `silent = true` was set by default 🤦🏻‍♀️. Thanks for your help! 🚀
